language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database makers_bnb_test;' -U postgres
  - psql -U postgres -d makers_bnb_test -f db/migrations/01_create_user_table.sql
  - psql -U postgres -d makers_bnb_test -f db/migrations/02_user_table_altered_no_duplicates.sql
  - psql -U postgres -d makers_bnb_test -f db/migrations/03_create_listings_table.sql
  - psql -U postgres -d makers_bnb_test -f db/migrations/04_add_user_id_foreign_key_column.sql
  - psql -U postgres -d makers_bnb_test -f db/migrations/05_create_pictures_table.sql
  - psql -U postgres -d makers_bnb_test -f db/migrations/06_alter_pictures_table.sql
  - psql -U postgres -d makers_bnb_test -f db/migrations/07_create_availability_table.sql
  - psql -U postgres -d makers_bnb_test -f db/migrations/08_create_bookings_table.sql

script:
  - bundle exec rspec
