name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.224.0
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: Start postgresql
      run: sudo systemctl start postgresql.service
    - name: Set up the test database
      run: |
        - psql -U postgres -c 'CREATE DATABASE makers_bnb_test;'
        - psql -U postgres -d makers_bnb_test -f db/migrations/01_create_user_table.sql
        - psql -U postgres -d makers_bnb_test -f db/migrations/02_user_table_altered_no_duplicates.sql
        - psql -U postgres -d makers_bnb_test -f db/migrations/03_create_listings_table.sql
        - psql -U postgres -d makers_bnb_test -f db/migrations/04_add_user_id_foreign_key_column.sql
        - psql -U postgres -d makers_bnb_test -f db/migrations/05_create_pictures_table.sql
        - psql -U postgres -d makers_bnb_test -f db/migrations/06_alter_pictures_table.sql
        - psql -U postgres -d makers_bnb_test -f db/migrations/07_create_availability_table.sql
        - psql -U postgres -d makers_bnb_test -f db/migrations/08_create_bookings_table.sql
    - name: Run tests
      run: bundle exec rspec
