# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Set up the test database
      run: |
        - PGPASSWORD=postgres psql -U postgres -c 'CREATE DATABASE makers_bnb_test;'
        - PGPASSWORD=postgres psql -U postgres -d makers_bnb_test -f db/migrations/01_create_user_table.sql
        - PGPASSWORD=postgres psql -U postgres -d makers_bnb_test -f db/migrations/02_user_table_altered_no_duplicates.sql
        - PGPASSWORD=postgres psql -U postgres -d makers_bnb_test -f db/migrations/03_create_listings_table.sql
        - PGPASSWORD=postgres psql -U postgres -d makers_bnb_test -f db/migrations/04_add_user_id_foreign_key_column.sql
        - PGPASSWORD=postgres psql -U postgres -d makers_bnb_test -f db/migrations/05_create_pictures_table.sql
        - PGPASSWORD=postgres psql -U postgres -d makers_bnb_test -f db/migrations/06_alter_pictures_table.sql
        - PGPASSWORD=postgres psql -U postgres -d makers_bnb_test -f db/migrations/07_create_availability_table.sql
        - PGPASSWORD=postgres psql -U postgres -d makers_bnb_test -f db/migrations/08_create_bookings_table.sql
      env:
        # The hostname used to communicate with the PostgreSQL service container
        POSTGRES_HOST: localhost
        # The default PostgreSQL port
        POSTGRES_PORT: 5432
    - name: Run tests
      run: bundle exec rspec
